# Generated by Django 2.2.10 on 2020-08-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corruption',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='corruption',
            name='phone',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
