# Generated by Django 2.2.10 on 2020-08-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_corruption_police'),
    ]

    operations = [
        migrations.AddField(
            model_name='corruption',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
